import os
import telebot
import time
from io import BytesIO
from pypdf import PdfReader          # ← Changed to pypdf
from groq import Groq
from fpdf import FPDF

# ================== ENVIRONMENT VARIABLES (for Render) ==================
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not TELEGRAM_TOKEN or not GROQ_API_KEY:
    raise ValueError("❌ TELEGRAM_TOKEN and GROQ_API_KEY must be set in environment variables!")

bot = telebot.TeleBot(TELEGRAM_TOKEN)
client = Groq(api_key=GROQ_API_KEY)

user_data = {}  # user_id -> {"jd": text}

# ===========================================

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Tailored Resume', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by ResumeEnhancerForRambot', 0, 0, 'C')

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message,
        "👋 Welcome to Resume Enhancer Bot!\n\n"
        "How to use:\n"
        "1. Send the **Job Description** first (paste text)\n"
        "2. Send your **Resume as PDF**\n\n"
        "Commands:\n"
        "/restart - Clear and start over\n"
        "/exit or /cancel - Clear session"
    )

@bot.message_handler(commands=['restart', 'exit', 'cancel'])
def handle_clear(message):
    user_id = message.from_user.id
    user_data.pop(user_id, None)
    bot.reply_to(message, "✅ Session cleared! Send a new Job Description to begin.")

@bot.message_handler(func=lambda m: True, content_types=['text'])
def handle_job_description(message):
    if message.text.startswith('/'):
        return

    user_id = message.from_user.id
    user_data[user_id] = {"jd": message.text.strip()}

    bot.reply_to(message, 
        "✅ Job Description saved!\n\n"
        "Now send your **resume as PDF** file."
    )

@bot.message_handler(content_types=['document'])
def handle_pdf(message):
    user_id = message.from_user.id

    if user_id not in user_data or "jd" not in user_data[user_id]:
        bot.reply_to(message, "⚠️ Please send the Job Description first.\nUse /restart or /exit.")
        return

    if not message.document.file_name.lower().endswith('.pdf'):
        bot.reply_to(message, "❌ Please send a valid PDF resume.")
        return

    processing_msg = bot.reply_to(message, "⏳ Processing your resume with AI... (10-40 seconds)")

    try:
        # Download PDF as bytes
        file_info = bot.get_file(message.document.file_id)
        downloaded_bytes = bot.download_file(file_info.file_path)

        # IMPORTANT FIX: Wrap bytes with BytesIO (fixes 'bytes' object has no attribute 'seek')
        pdf_stream = BytesIO(downloaded_bytes)

        # Use pypdf
        reader = PdfReader(pdf_stream)
        resume_text = "\n".join([page.extract_text() or "" for page in reader.pages]).strip()

        if len(resume_text) < 30:
            raise ValueError("Could not extract enough text from the PDF. Please use a text-selectable PDF.")

        jd = user_data[user_id]["jd"]

        # Safety: prevent very large inputs
        if len(resume_text) > 10000:
            resume_text = resume_text[:9500]

        prompt = f"""You are an expert ATS-friendly resume writer.

Job Description:
{jd}

Original Resume:
{resume_text}

Tailor the resume perfectly for this job:
- Naturally include exact keywords from the JD
- Strengthen bullet points (achievement-focused)
- Keep it concise (ideally 1 page)
- Professional tone, standard sections only
- Output **ONLY** the full enhanced resume in clean Markdown format. No extra comments."""

        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.6,
            max_tokens=4000
        )

        enhanced_md = completion.choices[0].message.content.strip()

        # Generate PDF
        pdf = PDF()
        pdf.add_page()
        pdf.set_font("Arial", size=11)

        for line in enhanced_md.split('\n'):
            safe_line = line.encode('latin-1', errors='replace').decode('latin-1')
            pdf.multi_cell(0, 6.5, safe_line)

        pdf_path = f"enhanced_{user_id}_{int(time.time())}.pdf"
        pdf.output(pdf_path)

        # Send enhanced resume
        with open(pdf_path, 'rb') as f:
            bot.send_document(
                message.chat.id,
                f,
                caption="✅ Your tailored resume is ready!\n\nPlease review it before submitting."
            )

        os.remove(pdf_path)
        user_data.pop(user_id, None)

    except Exception as e:
        error_str = str(e).lower()
        if "429" in error_str or "rate limit" in error_str:
            user_msg = "❌ Groq rate limit reached. Wait 30-60 seconds and try again."
        elif "413" in error_str or "too large" in error_str:
            user_msg = "❌ Input too long. Shorten your JD or use a smaller PDF."
        else:
            user_msg = f"❌ Error: {str(e)[:180]}\n\nUse /restart or /exit and try again."

        bot.edit_message_text(
            chat_id=processing_msg.chat.id,
            message_id=processing_msg.message_id,
            text=user_msg
        )

if __name__ == "__main__":
    print("🚀 Resume Enhancer Bot is running...")
    bot.infinity_polling()