import os
import telebot
from telebot import types
import time
from pypdf2 import PdfReader
from groq import Groq
from fpdf import FPDF

# ================== CONFIG FROM ENVIRONMENT ==================
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not TELEGRAM_TOKEN or not GROQ_API_KEY:
    raise ValueError("❌ Missing environment variables! Please set TELEGRAM_TOKEN and GROQ_API_KEY")

bot = telebot.TeleBot(TELEGRAM_TOKEN)
client = Groq(api_key=GROQ_API_KEY)

# In-memory storage: user_id -> job_description
user_data = {}

# ===========================================

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Tailored Resume', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by ResumeEnhancerForRambot', 0, 0, 'C')

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, 
        "👋 Welcome to Resume Enhancer Bot!\n\n"
        "How it works:\n"
        "1. Send the **Job Description** first (paste the text)\n"
        "2. Then send your **Resume as PDF**\n\n"
        "I'll tailor your CV to the job and return an enhanced PDF.\n\n"
        "Send /start anytime to reset."
    )

@bot.message_handler(func=lambda m: True, content_types=['text'])
def handle_job_description(message):
    if message.text.startswith('/'):
        return

    user_id = message.from_user.id
    user_data[user_id] = {"jd": message.text.strip()}

    bot.reply_to(message, 
        "✅ Job Description saved!\n\n"
        "Now please send your **resume PDF** file."
    )

@bot.message_handler(content_types=['document'])
def handle_pdf(message):
    user_id = message.from_user.id

    if user_id not in user_data or "jd" not in user_data[user_id]:
        bot.reply_to(message, "⚠️ Please send the Job Description first, then upload your PDF resume.")
        return

    if not message.document.file_name.lower().endswith('.pdf'):
        bot.reply_to(message, "❌ Please send a valid PDF resume.")
        return

    processing_msg = bot.reply_to(message, "⏳ Downloading resume... Sending to AI for tailoring... (10-25 seconds)")

    try:
        # Download PDF
        file_info = bot.get_file(message.document.file_id)
        downloaded_file = bot.download_file(file_info.file_path)

        # Extract text
        reader = PdfReader(downloaded_file)
        resume_text = "\n".join([page.extract_text() or "" for page in reader.pages]).strip()

        jd = user_data[user_id]["jd"]

        # Strong prompting for best results
        prompt = f"""You are a senior resume writer and ATS optimization expert.

Job Description:
{jd}

Original Resume:
{resume_text}

Rewrite this resume to be perfectly tailored for the job:
- Naturally incorporate exact keywords and phrases from the JD
- Make bullet points achievement-oriented and impactful
- Keep the resume to 1 page (concise and clean)
- Use professional language
- Standard sections only (no tables, columns, or graphics)
- Output **only** the full enhanced resume in clean Markdown format.

Do not add any extra comments."""

        # Call Groq
        completion = client.chat.completions.create(
            model="llama-3.3-70b-versatile",   # Fast + good quality on Groq
            messages=[{"role": "user", "content": prompt}],
            temperature=0.6,
            max_tokens=4000
        )

        enhanced_md = completion.choices[0].message.content.strip()

        # Generate PDF
        pdf = PDF()
        pdf.add_page()
        pdf.set_font("Arial", size=11)

        for line in enhanced_md.split('\n'):
            safe_line = line.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6.5, safe_line)

        pdf_path = f"enhanced_{user_id}_{int(time.time())}.pdf"
        pdf.output(pdf_path)

        # Send result
        with open(pdf_path, 'rb') as f:
            bot.send_document(
                message.chat.id,
                f,
                caption="✅ Your tailored resume is ready!\n\n"
                        "💡 Tip: Review it once before using."
            )

        # Cleanup
        os.remove(pdf_path)
        user_data.pop(user_id, None)   # Reset for this user

    except Exception as e:
        bot.edit_message_text(
            chat_id=processing_msg.chat.id,
            message_id=processing_msg.message_id,
            text=f"❌ Error occurred: {str(e)}\n\nPlease try again with a shorter JD or cleaner PDF."
        )
    finally:
        # Optional: delete the "processing" message after some time if needed
        pass

# ====================== START BOT ======================
if __name__ == "__main__":
    print("🚀 Resume Enhancer Bot is running...")
    bot.infinity_polling()